version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm-minor-and-patch:
        applies-to: version-updates
        patterns:
          - '*'
        update-types:
          - minor
          - patch
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    groups:
      docker-minor-and-patch:
        applies-to: version-updates
        patterns:
          - '*'
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions-minor-and-patch:
        applies-to: version-updates
        patterns:
          - '*'
        update-types:
          - minor
          - patch
